edition = "2021"
unstable_features = true
newline_style = "Unix"

# imports
reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"

# comments
normalize_comments = true
wrap_comments = true
format_code_in_doc_comments = true
