[package]
name = "core-tracing"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
test = false

[features]
console = ["console-subscriber"]

[dependencies] # In alphabetical order
console-subscriber = { version = "0.1.1", optional = true }
once_cell = "1.9.0"
opentelemetry = { version = "0.17.0", default-features = false, features = [
    "trace",
    "rt-tokio",
] }
opentelemetry-jaeger = { version = "0.16.0", features = ["rt-tokio"] }
tonic = "0.4"
tracing = "0.1.30"
tracing-appender = "0.2.0"
tracing-bunyan-formatter = "0.3.2"
tracing-futures = { version = "0.2.5", features = ["futures-03"] }
tracing-opentelemetry = "0.17.0"
tracing-subscriber = { version = "0.3.8", features = ["env-filter"] }
