name: assignme-command
on:
  repository_dispatch:
    types: [assignme-command]
jobs:
  assignme:
    runs-on: ubuntu-latest
    steps:
      # - name: Add reaction
      #   uses: peter-evans/create-or-update-comment@v2
      #   with:
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
      #     comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
      #     reactions: rocket
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          number: ${{ github.event.client_payload.github.payload.issue.number }}
          assignees: ${{ github.actor }}
