name: issue welcome
on:
  issues:
    types:
      - opened

# https://github.com/marketplace/actions/create-or-update-comment

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            👋 Thanks for opening this issue!

            Get help or engage by:

            - `/help` : to print help messages.
            - `/assignme` : to assign this issue to you.

