# merge pull request when it labled with approved

name: Merge branch with labeled
on:
  pull_request:
    types: [labeled]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Merge by labeled
        uses: devmasx/merge-branch@master
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          label_name: 'approved'
          target_branch: 'master'